// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"
    "baml_devkit/types"
    "baml_devkit/stream_types"

     _ "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

var typeMap = map[string]reflect.Type{
"TYPES.CreativeExplorerOutput": reflect.TypeOf(types.CreativeExplorerOutput{}),
    "STREAM_TYPES.CreativeExplorerOutput": reflect.TypeOf(stream_types.CreativeExplorerOutput{}),
"TYPES.FindingSeverity": reflect.TypeOf(types.FindingSeverity{}),
    "STREAM_TYPES.FindingSeverity": reflect.TypeOf(stream_types.FindingSeverity{}),
"TYPES.GeneralAnalystOutput": reflect.TypeOf(types.GeneralAnalystOutput{}),
    "STREAM_TYPES.GeneralAnalystOutput": reflect.TypeOf(stream_types.GeneralAnalystOutput{}),
"TYPES.PRDescription": reflect.TypeOf(types.PRDescription{}),
    "STREAM_TYPES.PRDescription": reflect.TypeOf(stream_types.PRDescription{}),
"TYPES.RoleOutput": reflect.TypeOf(types.RoleOutput{}),
    "STREAM_TYPES.RoleOutput": reflect.TypeOf(stream_types.RoleOutput{}),
"TYPES.SecurityReviewerOutput": reflect.TypeOf(types.SecurityReviewerOutput{}),
    "STREAM_TYPES.SecurityReviewerOutput": reflect.TypeOf(stream_types.SecurityReviewerOutput{}),
"TYPES.StrictCriticOutput": reflect.TypeOf(types.StrictCriticOutput{}),
    "STREAM_TYPES.StrictCriticOutput": reflect.TypeOf(stream_types.StrictCriticOutput{}),








}