// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"fmt"
    "context"

    "baml_devkit/types"
    _ "baml_devkit/stream_types"
    baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type parse struct {}
var Parse = &parse{}


/// Parse version of AnalyzeBranchCreativeExplorer (Takes in string and returns types.CreativeExplorerOutput)
func (*parse) AnalyzeBranchCreativeExplorer(text string, opts ...CallOptionFunc) (types.CreativeExplorerOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchCreativeExplorer: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeBranchCreativeExplorer", encoded)
    if err != nil {
        return types.CreativeExplorerOutput{}, err
    }

    casted := (result).(types.CreativeExplorerOutput)

    return casted, nil
}

/// Parse version of AnalyzeBranchDefault (Takes in string and returns types.RoleOutput)
func (*parse) AnalyzeBranchDefault(text string, opts ...CallOptionFunc) (types.RoleOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchDefault: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeBranchDefault", encoded)
    if err != nil {
        return types.RoleOutput{}, err
    }

    casted := (result).(types.RoleOutput)

    return casted, nil
}

/// Parse version of AnalyzeBranchGeneralAnalyst (Takes in string and returns types.GeneralAnalystOutput)
func (*parse) AnalyzeBranchGeneralAnalyst(text string, opts ...CallOptionFunc) (types.GeneralAnalystOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchGeneralAnalyst: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeBranchGeneralAnalyst", encoded)
    if err != nil {
        return types.GeneralAnalystOutput{}, err
    }

    casted := (result).(types.GeneralAnalystOutput)

    return casted, nil
}

/// Parse version of AnalyzeBranchSecurityReviewer (Takes in string and returns types.SecurityReviewerOutput)
func (*parse) AnalyzeBranchSecurityReviewer(text string, opts ...CallOptionFunc) (types.SecurityReviewerOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchSecurityReviewer: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeBranchSecurityReviewer", encoded)
    if err != nil {
        return types.SecurityReviewerOutput{}, err
    }

    casted := (result).(types.SecurityReviewerOutput)

    return casted, nil
}

/// Parse version of AnalyzeBranchStrictCritic (Takes in string and returns types.StrictCriticOutput)
func (*parse) AnalyzeBranchStrictCritic(text string, opts ...CallOptionFunc) (types.StrictCriticOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchStrictCritic: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeBranchStrictCritic", encoded)
    if err != nil {
        return types.StrictCriticOutput{}, err
    }

    casted := (result).(types.StrictCriticOutput)

    return casted, nil
}

/// Parse version of AnalyzeLogPatterns (Takes in string and returns types.LogPatternOutput)
func (*parse) AnalyzeLogPatterns(text string, opts ...CallOptionFunc) (types.LogPatternOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeLogPatterns: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeLogPatterns", encoded)
    if err != nil {
        return types.LogPatternOutput{}, err
    }

    casted := (result).(types.LogPatternOutput)

    return casted, nil
}

/// Parse version of AnalyzeMigration (Takes in string and returns types.MigrateOutput)
func (*parse) AnalyzeMigration(text string, opts ...CallOptionFunc) (types.MigrateOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeMigration: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeMigration", encoded)
    if err != nil {
        return types.MigrateOutput{}, err
    }

    casted := (result).(types.MigrateOutput)

    return casted, nil
}

/// Parse version of AnalyzeProfile (Takes in string and returns types.ProfileOutput)
func (*parse) AnalyzeProfile(text string, opts ...CallOptionFunc) (types.ProfileOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeProfile: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeProfile", encoded)
    if err != nil {
        return types.ProfileOutput{}, err
    }

    casted := (result).(types.ProfileOutput)

    return casted, nil
}

/// Parse version of AnalyzeRepoHealth (Takes in string and returns types.HealthReport)
func (*parse) AnalyzeRepoHealth(text string, opts ...CallOptionFunc) (types.HealthReport, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeRepoHealth: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeRepoHealth", encoded)
    if err != nil {
        return types.HealthReport{}, err
    }

    casted := (result).(types.HealthReport)

    return casted, nil
}

/// Parse version of DraftADR (Takes in string and returns types.ADROutput)
func (*parse) DraftADR(text string, opts ...CallOptionFunc) (types.ADROutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DraftADR: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "DraftADR", encoded)
    if err != nil {
        return types.ADROutput{}, err
    }

    casted := (result).(types.ADROutput)

    return casted, nil
}

/// Parse version of DraftIncidentReport (Takes in string and returns types.IncidentOutput)
func (*parse) DraftIncidentReport(text string, opts ...CallOptionFunc) (types.IncidentOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DraftIncidentReport: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "DraftIncidentReport", encoded)
    if err != nil {
        return types.IncidentOutput{}, err
    }

    casted := (result).(types.IncidentOutput)

    return casted, nil
}

/// Parse version of DraftPR (Takes in string and returns types.PRDescription)
func (*parse) DraftPR(text string, opts ...CallOptionFunc) (types.PRDescription, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DraftPR: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "DraftPR", encoded)
    if err != nil {
        return types.PRDescription{}, err
    }

    casted := (result).(types.PRDescription)

    return casted, nil
}

/// Parse version of GenerateDocs (Takes in string and returns types.DocgenOutput)
func (*parse) GenerateDocs(text string, opts ...CallOptionFunc) (types.DocgenOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateDocs: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "GenerateDocs", encoded)
    if err != nil {
        return types.DocgenOutput{}, err
    }

    casted := (result).(types.DocgenOutput)

    return casted, nil
}

/// Parse version of GenerateScaffold (Takes in string and returns types.ScaffoldOutput)
func (*parse) GenerateScaffold(text string, opts ...CallOptionFunc) (types.ScaffoldOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateScaffold: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "GenerateScaffold", encoded)
    if err != nil {
        return types.ScaffoldOutput{}, err
    }

    casted := (result).(types.ScaffoldOutput)

    return casted, nil
}

/// Parse version of TriageCIFailure (Takes in string and returns types.CITriageReport)
func (*parse) TriageCIFailure(text string, opts ...CallOptionFunc) (types.CITriageReport, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "text": text, "stream": false },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TriageCIFailure: %w", err)
        panic(wrapped_err)
    }

    result, err := bamlRuntime.CallFunctionParse(context.Background(), "TriageCIFailure", encoded)
    if err != nil {
        return types.CITriageReport{}, err
    }

    casted := (result).(types.CITriageReport)

    return casted, nil
}
