// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"fmt"
    "context"

    _ "baml_devkit/types"
    baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type build_request_stream struct {}
var StreamRequest = &build_request_stream{}


// Build streaming HTTP request for AnalyzeBranchCreativeExplorer (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeBranchCreativeExplorer(prompt string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchCreativeExplorer: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeBranchCreativeExplorer", encoded)
}

// Build streaming HTTP request for AnalyzeBranchDefault (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeBranchDefault(prompt string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchDefault: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeBranchDefault", encoded)
}

// Build streaming HTTP request for AnalyzeBranchGeneralAnalyst (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeBranchGeneralAnalyst(prompt string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchGeneralAnalyst: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeBranchGeneralAnalyst", encoded)
}

// Build streaming HTTP request for AnalyzeBranchSecurityReviewer (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeBranchSecurityReviewer(prompt string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchSecurityReviewer: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeBranchSecurityReviewer", encoded)
}

// Build streaming HTTP request for AnalyzeBranchStrictCritic (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeBranchStrictCritic(prompt string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchStrictCritic: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeBranchStrictCritic", encoded)
}

// Build streaming HTTP request for AnalyzeLogPatterns (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeLogPatterns(logs string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "logs": logs, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeLogPatterns: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeLogPatterns", encoded)
}

// Build streaming HTTP request for AnalyzeMigration (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeMigration(old_api string,new_api string,code string,file_path string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "old_api": old_api, "new_api": new_api, "code": code, "file_path": file_path, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeMigration: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeMigration", encoded)
}

// Build streaming HTTP request for AnalyzeProfile (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeProfile(input string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "input": input, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeProfile: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeProfile", encoded)
}

// Build streaming HTTP request for AnalyzeRepoHealth (returns baml.HTTPRequest)
func (*build_request_stream) AnalyzeRepoHealth(repo_context string,check_results string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "repo_context": repo_context, "check_results": check_results, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeRepoHealth: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "AnalyzeRepoHealth", encoded)
}

// Build streaming HTTP request for DraftADR (returns baml.HTTPRequest)
func (*build_request_stream) DraftADR(title string,ctx_text string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "title": title, "ctx_text": ctx_text, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DraftADR: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "DraftADR", encoded)
}

// Build streaming HTTP request for DraftIncidentReport (returns baml.HTTPRequest)
func (*build_request_stream) DraftIncidentReport(description string,logs string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "description": description, "logs": logs, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DraftIncidentReport: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "DraftIncidentReport", encoded)
}

// Build streaming HTTP request for DraftPR (returns baml.HTTPRequest)
func (*build_request_stream) DraftPR(prompt string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DraftPR: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "DraftPR", encoded)
}

// Build streaming HTTP request for GenerateDocs (returns baml.HTTPRequest)
func (*build_request_stream) GenerateDocs(file_content string,file_path string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "file_content": file_content, "file_path": file_path, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateDocs: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "GenerateDocs", encoded)
}

// Build streaming HTTP request for GenerateScaffold (returns baml.HTTPRequest)
func (*build_request_stream) GenerateScaffold(package_name string,purpose string,repo_context string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "package_name": package_name, "purpose": purpose, "repo_context": repo_context, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateScaffold: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "GenerateScaffold", encoded)
}

// Build streaming HTTP request for TriageCIFailure (returns baml.HTTPRequest)
func (*build_request_stream) TriageCIFailure(log string,repo_context string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "log": log, "repo_context": repo_context, "stream": true },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TriageCIFailure: %w", err)
        panic(wrapped_err)
    }

    return bamlRuntime.BuildRequest(context.Background(), "TriageCIFailure", encoded)
}
