// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"
    "baml_devkit/types"
    "baml_devkit/stream_types"

     _ "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

var typeMap = map[string]reflect.Type{
"TYPES.ADROutput": reflect.TypeOf(types.ADROutput{}),
    "STREAM_TYPES.ADROutput": reflect.TypeOf(stream_types.ADROutput{}),
"TYPES.CITriageReport": reflect.TypeOf(types.CITriageReport{}),
    "STREAM_TYPES.CITriageReport": reflect.TypeOf(stream_types.CITriageReport{}),
"TYPES.CreativeExplorerOutput": reflect.TypeOf(types.CreativeExplorerOutput{}),
    "STREAM_TYPES.CreativeExplorerOutput": reflect.TypeOf(stream_types.CreativeExplorerOutput{}),
"TYPES.DocgenOutput": reflect.TypeOf(types.DocgenOutput{}),
    "STREAM_TYPES.DocgenOutput": reflect.TypeOf(stream_types.DocgenOutput{}),
"TYPES.FailingJob": reflect.TypeOf(types.FailingJob{}),
    "STREAM_TYPES.FailingJob": reflect.TypeOf(stream_types.FailingJob{}),
"TYPES.FindingSeverity": reflect.TypeOf(types.FindingSeverity{}),
    "STREAM_TYPES.FindingSeverity": reflect.TypeOf(stream_types.FindingSeverity{}),
"TYPES.GeneralAnalystOutput": reflect.TypeOf(types.GeneralAnalystOutput{}),
    "STREAM_TYPES.GeneralAnalystOutput": reflect.TypeOf(stream_types.GeneralAnalystOutput{}),
"TYPES.HealthCheck": reflect.TypeOf(types.HealthCheck{}),
    "STREAM_TYPES.HealthCheck": reflect.TypeOf(stream_types.HealthCheck{}),
"TYPES.HealthReport": reflect.TypeOf(types.HealthReport{}),
    "STREAM_TYPES.HealthReport": reflect.TypeOf(stream_types.HealthReport{}),
"TYPES.IncidentAction": reflect.TypeOf(types.IncidentAction{}),
    "STREAM_TYPES.IncidentAction": reflect.TypeOf(stream_types.IncidentAction{}),
"TYPES.IncidentOutput": reflect.TypeOf(types.IncidentOutput{}),
    "STREAM_TYPES.IncidentOutput": reflect.TypeOf(stream_types.IncidentOutput{}),
"TYPES.LogPatternEntry": reflect.TypeOf(types.LogPatternEntry{}),
    "STREAM_TYPES.LogPatternEntry": reflect.TypeOf(stream_types.LogPatternEntry{}),
"TYPES.LogPatternOutput": reflect.TypeOf(types.LogPatternOutput{}),
    "STREAM_TYPES.LogPatternOutput": reflect.TypeOf(stream_types.LogPatternOutput{}),
"TYPES.MigrateOutput": reflect.TypeOf(types.MigrateOutput{}),
    "STREAM_TYPES.MigrateOutput": reflect.TypeOf(stream_types.MigrateOutput{}),
"TYPES.PRDescription": reflect.TypeOf(types.PRDescription{}),
    "STREAM_TYPES.PRDescription": reflect.TypeOf(stream_types.PRDescription{}),
"TYPES.ProfileHotspot": reflect.TypeOf(types.ProfileHotspot{}),
    "STREAM_TYPES.ProfileHotspot": reflect.TypeOf(stream_types.ProfileHotspot{}),
"TYPES.ProfileOutput": reflect.TypeOf(types.ProfileOutput{}),
    "STREAM_TYPES.ProfileOutput": reflect.TypeOf(stream_types.ProfileOutput{}),
"TYPES.ReproductionSteps": reflect.TypeOf(types.ReproductionSteps{}),
    "STREAM_TYPES.ReproductionSteps": reflect.TypeOf(stream_types.ReproductionSteps{}),
"TYPES.RoleOutput": reflect.TypeOf(types.RoleOutput{}),
    "STREAM_TYPES.RoleOutput": reflect.TypeOf(stream_types.RoleOutput{}),
"TYPES.RootCause": reflect.TypeOf(types.RootCause{}),
    "STREAM_TYPES.RootCause": reflect.TypeOf(stream_types.RootCause{}),
"TYPES.ScaffoldOutput": reflect.TypeOf(types.ScaffoldOutput{}),
    "STREAM_TYPES.ScaffoldOutput": reflect.TypeOf(stream_types.ScaffoldOutput{}),
"TYPES.SecurityReviewerOutput": reflect.TypeOf(types.SecurityReviewerOutput{}),
    "STREAM_TYPES.SecurityReviewerOutput": reflect.TypeOf(stream_types.SecurityReviewerOutput{}),
"TYPES.StrictCriticOutput": reflect.TypeOf(types.StrictCriticOutput{}),
    "STREAM_TYPES.StrictCriticOutput": reflect.TypeOf(stream_types.StrictCriticOutput{}),
"TYPES.SuggestedFix": reflect.TypeOf(types.SuggestedFix{}),
    "STREAM_TYPES.SuggestedFix": reflect.TypeOf(stream_types.SuggestedFix{}),

"TYPES.Confidence": reflect.TypeOf(types.Confidence("")),
"TYPES.LogPatternSeverity": reflect.TypeOf(types.LogPatternSeverity("")),







}