// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"


type CreativeExplorerOutputClassView struct {
    inner baml.ClassBuilder
}

func (t *CreativeExplorerOutputClassView) ListProperties() ([]ClassPropertyView, error) {
    result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}




func (t *CreativeExplorerOutputClassView) PropertyHealth_score() (ClassPropertyView, error) {
    return t.inner.Property("health_score")
}

func (t *CreativeExplorerOutputClassView) PropertySummary() (ClassPropertyView, error) {
    return t.inner.Property("summary")
}

func (t *CreativeExplorerOutputClassView) PropertyRecommendations() (ClassPropertyView, error) {
    return t.inner.Property("recommendations")
}

func (t *CreativeExplorerOutputClassView) PropertyInnovation_opportunities() (ClassPropertyView, error) {
    return t.inner.Property("innovation_opportunities")
}

func (t *CreativeExplorerOutputClassView) PropertyArchitectural_potential() (ClassPropertyView, error) {
    return t.inner.Property("architectural_potential")
}


func (t *TypeBuilder) CreativeExplorerOutput() (*CreativeExplorerOutputClassView, error) {
	bld, err := t.inner.Class("CreativeExplorerOutput")
	if err != nil {
		return nil, err
	}
	return &CreativeExplorerOutputClassView{inner: bld}, nil
}

func (t *CreativeExplorerOutputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FindingSeverityClassView struct {
    inner baml.ClassBuilder
}

func (t *FindingSeverityClassView) ListProperties() ([]ClassPropertyView, error) {
    result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}




func (t *FindingSeverityClassView) PropertyDescription() (ClassPropertyView, error) {
    return t.inner.Property("description")
}

func (t *FindingSeverityClassView) PropertySeverity() (ClassPropertyView, error) {
    return t.inner.Property("severity")
}


func (t *TypeBuilder) FindingSeverity() (*FindingSeverityClassView, error) {
	bld, err := t.inner.Class("FindingSeverity")
	if err != nil {
		return nil, err
	}
	return &FindingSeverityClassView{inner: bld}, nil
}

func (t *FindingSeverityClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GeneralAnalystOutputClassView struct {
    inner baml.ClassBuilder
}

func (t *GeneralAnalystOutputClassView) ListProperties() ([]ClassPropertyView, error) {
    result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}




func (t *GeneralAnalystOutputClassView) PropertyHealth_score() (ClassPropertyView, error) {
    return t.inner.Property("health_score")
}

func (t *GeneralAnalystOutputClassView) PropertySummary() (ClassPropertyView, error) {
    return t.inner.Property("summary")
}

func (t *GeneralAnalystOutputClassView) PropertyRecommendations() (ClassPropertyView, error) {
    return t.inner.Property("recommendations")
}

func (t *GeneralAnalystOutputClassView) PropertyGaps() (ClassPropertyView, error) {
    return t.inner.Property("gaps")
}

func (t *GeneralAnalystOutputClassView) PropertyWork_patterns() (ClassPropertyView, error) {
    return t.inner.Property("work_patterns")
}


func (t *TypeBuilder) GeneralAnalystOutput() (*GeneralAnalystOutputClassView, error) {
	bld, err := t.inner.Class("GeneralAnalystOutput")
	if err != nil {
		return nil, err
	}
	return &GeneralAnalystOutputClassView{inner: bld}, nil
}

func (t *GeneralAnalystOutputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PRDescriptionClassView struct {
    inner baml.ClassBuilder
}

func (t *PRDescriptionClassView) ListProperties() ([]ClassPropertyView, error) {
    result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}




func (t *PRDescriptionClassView) PropertyTitle() (ClassPropertyView, error) {
    return t.inner.Property("title")
}

func (t *PRDescriptionClassView) PropertySummary() (ClassPropertyView, error) {
    return t.inner.Property("summary")
}

func (t *PRDescriptionClassView) PropertyChanges() (ClassPropertyView, error) {
    return t.inner.Property("changes")
}

func (t *PRDescriptionClassView) PropertyTest_plan() (ClassPropertyView, error) {
    return t.inner.Property("test_plan")
}


func (t *TypeBuilder) PRDescription() (*PRDescriptionClassView, error) {
	bld, err := t.inner.Class("PRDescription")
	if err != nil {
		return nil, err
	}
	return &PRDescriptionClassView{inner: bld}, nil
}

func (t *PRDescriptionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RoleOutputClassView struct {
    inner baml.ClassBuilder
}

func (t *RoleOutputClassView) ListProperties() ([]ClassPropertyView, error) {
    result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}




func (t *RoleOutputClassView) PropertyHealth_score() (ClassPropertyView, error) {
    return t.inner.Property("health_score")
}

func (t *RoleOutputClassView) PropertySummary() (ClassPropertyView, error) {
    return t.inner.Property("summary")
}

func (t *RoleOutputClassView) PropertyRecommendations() (ClassPropertyView, error) {
    return t.inner.Property("recommendations")
}


func (t *TypeBuilder) RoleOutput() (*RoleOutputClassView, error) {
	bld, err := t.inner.Class("RoleOutput")
	if err != nil {
		return nil, err
	}
	return &RoleOutputClassView{inner: bld}, nil
}

func (t *RoleOutputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SecurityReviewerOutputClassView struct {
    inner baml.ClassBuilder
}

func (t *SecurityReviewerOutputClassView) ListProperties() ([]ClassPropertyView, error) {
    result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}




func (t *SecurityReviewerOutputClassView) PropertyHealth_score() (ClassPropertyView, error) {
    return t.inner.Property("health_score")
}

func (t *SecurityReviewerOutputClassView) PropertySummary() (ClassPropertyView, error) {
    return t.inner.Property("summary")
}

func (t *SecurityReviewerOutputClassView) PropertyRecommendations() (ClassPropertyView, error) {
    return t.inner.Property("recommendations")
}

func (t *SecurityReviewerOutputClassView) PropertyFindings() (ClassPropertyView, error) {
    return t.inner.Property("findings")
}


func (t *TypeBuilder) SecurityReviewerOutput() (*SecurityReviewerOutputClassView, error) {
	bld, err := t.inner.Class("SecurityReviewerOutput")
	if err != nil {
		return nil, err
	}
	return &SecurityReviewerOutputClassView{inner: bld}, nil
}

func (t *SecurityReviewerOutputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type StrictCriticOutputClassView struct {
    inner baml.ClassBuilder
}

func (t *StrictCriticOutputClassView) ListProperties() ([]ClassPropertyView, error) {
    result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}




func (t *StrictCriticOutputClassView) PropertyHealth_score() (ClassPropertyView, error) {
    return t.inner.Property("health_score")
}

func (t *StrictCriticOutputClassView) PropertySummary() (ClassPropertyView, error) {
    return t.inner.Property("summary")
}

func (t *StrictCriticOutputClassView) PropertyRecommendations() (ClassPropertyView, error) {
    return t.inner.Property("recommendations")
}

func (t *StrictCriticOutputClassView) PropertyRisks() (ClassPropertyView, error) {
    return t.inner.Property("risks")
}


func (t *TypeBuilder) StrictCriticOutput() (*StrictCriticOutputClassView, error) {
	bld, err := t.inner.Class("StrictCriticOutput")
	if err != nil {
		return nil, err
	}
	return &StrictCriticOutputClassView{inner: bld}, nil
}

func (t *StrictCriticOutputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
