// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

var file_map = map[string]string{
  
  "clients.baml": "client<llm> AnthropicBalanced {\n  provider anthropic\n  retry_policy CouncilRetry\n  options {\n    model \"claude-sonnet-4-6\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n\nclient<llm> OpenAIBalanced {\n  provider openai\n  retry_policy CouncilRetry\n  options {\n    model \"gpt-5.4\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nclient<llm> GeminiFast {\n  provider google-ai\n  retry_policy CouncilRetry\n  options {\n    model \"gemini-3-flash-preview\"\n    api_key env.GEMINI_API_KEY\n  }\n}\n\nretry_policy CouncilRetry {\n  max_retries 2\n  strategy {\n    type exponential_backoff\n    delay_ms 1000\n    multiplier 2\n  }\n}\n",  
  "council.baml": "class FindingSeverity {\n  description string\n  severity string @description(\"critical|high|medium|low|info\")\n}\n\nclass RoleOutput {\n  health_score float\n  summary string\n  recommendations string[]\n}\n\nclass StrictCriticOutput {\n  health_score float\n  summary string\n  recommendations string[]\n  risks string[]\n}\n\nclass CreativeExplorerOutput {\n  health_score float\n  summary string\n  recommendations string[]\n  innovation_opportunities string[]\n  architectural_potential string\n}\n\nclass SecurityReviewerOutput {\n  health_score float\n  summary string\n  recommendations string[]\n  findings FindingSeverity[]\n}\n\nclass GeneralAnalystOutput {\n  health_score float\n  summary string\n  recommendations string[]\n  gaps string[]\n  work_patterns string\n}\n\nfunction AnalyzeBranchStrictCritic(prompt: string) -> StrictCriticOutput {\n  client AnthropicBalanced\n  prompt #\"\n    {{ prompt }}\n  \"#\n}\n\nfunction AnalyzeBranchCreativeExplorer(prompt: string) -> CreativeExplorerOutput {\n  client AnthropicBalanced\n  prompt #\"\n    {{ prompt }}\n  \"#\n}\n\nfunction AnalyzeBranchSecurityReviewer(prompt: string) -> SecurityReviewerOutput {\n  client AnthropicBalanced\n  prompt #\"\n    {{ prompt }}\n  \"#\n}\n\nfunction AnalyzeBranchGeneralAnalyst(prompt: string) -> GeneralAnalystOutput {\n  client AnthropicBalanced\n  prompt #\"\n    {{ prompt }}\n  \"#\n}\n\nfunction AnalyzeBranchDefault(prompt: string) -> RoleOutput {\n  client AnthropicBalanced\n  prompt #\"\n    {{ prompt }}\n  \"#\n}\n",  
  "generators.baml": "generator target {\n  output_type \"go\"\n  output_dir \"../baml_client\"\n  version \"0.218.0\"\n  client_package_name \"baml_client\"\n}\n",  
  "pr.baml": "class PRDescription {\n  title string @description(\"Short PR title, ≤72 characters\")\n  summary string @description(\"2-4 sentence overview of what changed and why\")\n  changes string[] @description(\"Bullet list of key changes\")\n  test_plan string[] @description(\"Bullet list of how to verify the changes\")\n}\n\nfunction DraftPR(prompt: string) -> PRDescription {\n  client AnthropicBalanced\n  prompt #\"\n    {{ prompt }}\n  \"#\n}\n",  
}

func getBamlFiles() map[string]string {
  return file_map
}