// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"baml_client/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)



func AnalyzeBranchCreativeExplorer(ctx context.Context, prompt string, opts ...CallOptionFunc) (types.CreativeExplorerOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        panic(err)
    }

    if callOpts.onTick == nil {
        result, err := bamlRuntime.CallFunction(ctx, "AnalyzeBranchCreativeExplorer", encoded, callOpts.onTick)
        if err != nil {
            return types.CreativeExplorerOutput{}, err
        }

        if result.Error != nil {
            return types.CreativeExplorerOutput{}, result.Error
        }

        casted := (result.Data).(types.CreativeExplorerOutput)

        return casted, nil
    } else {
        channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchCreativeExplorer", encoded, callOpts.onTick)
        if err != nil {
            return types.CreativeExplorerOutput{}, err
        }

        for result := range channel {
            if result.Error != nil {
                return types.CreativeExplorerOutput{}, result.Error
            }

            if result.HasData {
                return result.Data.(types.CreativeExplorerOutput), nil
            }
        }

        return types.CreativeExplorerOutput{}, fmt.Errorf("No data returned from stream")
    }
}


func AnalyzeBranchDefault(ctx context.Context, prompt string, opts ...CallOptionFunc) (types.RoleOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        panic(err)
    }

    if callOpts.onTick == nil {
        result, err := bamlRuntime.CallFunction(ctx, "AnalyzeBranchDefault", encoded, callOpts.onTick)
        if err != nil {
            return types.RoleOutput{}, err
        }

        if result.Error != nil {
            return types.RoleOutput{}, result.Error
        }

        casted := (result.Data).(types.RoleOutput)

        return casted, nil
    } else {
        channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchDefault", encoded, callOpts.onTick)
        if err != nil {
            return types.RoleOutput{}, err
        }

        for result := range channel {
            if result.Error != nil {
                return types.RoleOutput{}, result.Error
            }

            if result.HasData {
                return result.Data.(types.RoleOutput), nil
            }
        }

        return types.RoleOutput{}, fmt.Errorf("No data returned from stream")
    }
}


func AnalyzeBranchGeneralAnalyst(ctx context.Context, prompt string, opts ...CallOptionFunc) (types.GeneralAnalystOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        panic(err)
    }

    if callOpts.onTick == nil {
        result, err := bamlRuntime.CallFunction(ctx, "AnalyzeBranchGeneralAnalyst", encoded, callOpts.onTick)
        if err != nil {
            return types.GeneralAnalystOutput{}, err
        }

        if result.Error != nil {
            return types.GeneralAnalystOutput{}, result.Error
        }

        casted := (result.Data).(types.GeneralAnalystOutput)

        return casted, nil
    } else {
        channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchGeneralAnalyst", encoded, callOpts.onTick)
        if err != nil {
            return types.GeneralAnalystOutput{}, err
        }

        for result := range channel {
            if result.Error != nil {
                return types.GeneralAnalystOutput{}, result.Error
            }

            if result.HasData {
                return result.Data.(types.GeneralAnalystOutput), nil
            }
        }

        return types.GeneralAnalystOutput{}, fmt.Errorf("No data returned from stream")
    }
}


func AnalyzeBranchSecurityReviewer(ctx context.Context, prompt string, opts ...CallOptionFunc) (types.SecurityReviewerOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        panic(err)
    }

    if callOpts.onTick == nil {
        result, err := bamlRuntime.CallFunction(ctx, "AnalyzeBranchSecurityReviewer", encoded, callOpts.onTick)
        if err != nil {
            return types.SecurityReviewerOutput{}, err
        }

        if result.Error != nil {
            return types.SecurityReviewerOutput{}, result.Error
        }

        casted := (result.Data).(types.SecurityReviewerOutput)

        return casted, nil
    } else {
        channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchSecurityReviewer", encoded, callOpts.onTick)
        if err != nil {
            return types.SecurityReviewerOutput{}, err
        }

        for result := range channel {
            if result.Error != nil {
                return types.SecurityReviewerOutput{}, result.Error
            }

            if result.HasData {
                return result.Data.(types.SecurityReviewerOutput), nil
            }
        }

        return types.SecurityReviewerOutput{}, fmt.Errorf("No data returned from stream")
    }
}


func AnalyzeBranchStrictCritic(ctx context.Context, prompt string, opts ...CallOptionFunc) (types.StrictCriticOutput, error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    // Resolve client option to clientRegistry (client takes precedence)
    if callOpts.client != nil {
        if callOpts.clientRegistry == nil {
            callOpts.clientRegistry = baml.NewClientRegistry()
        }
        callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        panic(err)
    }

    if callOpts.onTick == nil {
        result, err := bamlRuntime.CallFunction(ctx, "AnalyzeBranchStrictCritic", encoded, callOpts.onTick)
        if err != nil {
            return types.StrictCriticOutput{}, err
        }

        if result.Error != nil {
            return types.StrictCriticOutput{}, result.Error
        }

        casted := (result.Data).(types.StrictCriticOutput)

        return casted, nil
    } else {
        channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchStrictCritic", encoded, callOpts.onTick)
        if err != nil {
            return types.StrictCriticOutput{}, err
        }

        for result := range channel {
            if result.Error != nil {
                return types.StrictCriticOutput{}, result.Error
            }

            if result.HasData {
                return result.Data.(types.StrictCriticOutput), nil
            }
        }

        return types.StrictCriticOutput{}, fmt.Errorf("No data returned from stream")
    }
}
