// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"baml_client/baml_client/stream_types"
	"baml_client/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type stream struct {}
var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
    IsError   bool
    Error     error
    IsFinal   bool
    as_final  *TFinal
    as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() *TFinal {
    return s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() *TStream {
    return s.as_stream
}


/// Streaming version of AnalyzeBranchCreativeExplorer
func (*stream) AnalyzeBranchCreativeExplorer(ctx context.Context, prompt string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.CreativeExplorerOutput, types.CreativeExplorerOutput], error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchCreativeExplorer: %w", err)
        panic(wrapped_err)
    }

    internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchCreativeExplorer", encoded, callOpts.onTick)
    if err != nil {
        return nil, err
    }

    channel := make(chan StreamValue[stream_types.CreativeExplorerOutput, types.CreativeExplorerOutput])
    go func() {
        for result := range internal_channel {
            if result.Error != nil {
                channel <- StreamValue[stream_types.CreativeExplorerOutput, types.CreativeExplorerOutput]{
                    IsError: true,
                    Error:   result.Error,
                }
                close(channel)
                return
            }
            if result.HasData {
                    data := (result.Data).(types.CreativeExplorerOutput)
                    channel <- StreamValue[stream_types.CreativeExplorerOutput, types.CreativeExplorerOutput]{
                        IsFinal: true,
                        as_final: &data,
                    }
            } else {
                data := (result.StreamData).(stream_types.CreativeExplorerOutput)
                channel <- StreamValue[stream_types.CreativeExplorerOutput, types.CreativeExplorerOutput]{
                    IsFinal: false,
                    as_stream: &data,
                }
            }
        }

		// when internal_channel is closed, close the output too
		close(channel)
    }()
    return channel, nil
}

/// Streaming version of AnalyzeBranchDefault
func (*stream) AnalyzeBranchDefault(ctx context.Context, prompt string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.RoleOutput, types.RoleOutput], error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchDefault: %w", err)
        panic(wrapped_err)
    }

    internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchDefault", encoded, callOpts.onTick)
    if err != nil {
        return nil, err
    }

    channel := make(chan StreamValue[stream_types.RoleOutput, types.RoleOutput])
    go func() {
        for result := range internal_channel {
            if result.Error != nil {
                channel <- StreamValue[stream_types.RoleOutput, types.RoleOutput]{
                    IsError: true,
                    Error:   result.Error,
                }
                close(channel)
                return
            }
            if result.HasData {
                    data := (result.Data).(types.RoleOutput)
                    channel <- StreamValue[stream_types.RoleOutput, types.RoleOutput]{
                        IsFinal: true,
                        as_final: &data,
                    }
            } else {
                data := (result.StreamData).(stream_types.RoleOutput)
                channel <- StreamValue[stream_types.RoleOutput, types.RoleOutput]{
                    IsFinal: false,
                    as_stream: &data,
                }
            }
        }

		// when internal_channel is closed, close the output too
		close(channel)
    }()
    return channel, nil
}

/// Streaming version of AnalyzeBranchGeneralAnalyst
func (*stream) AnalyzeBranchGeneralAnalyst(ctx context.Context, prompt string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.GeneralAnalystOutput, types.GeneralAnalystOutput], error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchGeneralAnalyst: %w", err)
        panic(wrapped_err)
    }

    internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchGeneralAnalyst", encoded, callOpts.onTick)
    if err != nil {
        return nil, err
    }

    channel := make(chan StreamValue[stream_types.GeneralAnalystOutput, types.GeneralAnalystOutput])
    go func() {
        for result := range internal_channel {
            if result.Error != nil {
                channel <- StreamValue[stream_types.GeneralAnalystOutput, types.GeneralAnalystOutput]{
                    IsError: true,
                    Error:   result.Error,
                }
                close(channel)
                return
            }
            if result.HasData {
                    data := (result.Data).(types.GeneralAnalystOutput)
                    channel <- StreamValue[stream_types.GeneralAnalystOutput, types.GeneralAnalystOutput]{
                        IsFinal: true,
                        as_final: &data,
                    }
            } else {
                data := (result.StreamData).(stream_types.GeneralAnalystOutput)
                channel <- StreamValue[stream_types.GeneralAnalystOutput, types.GeneralAnalystOutput]{
                    IsFinal: false,
                    as_stream: &data,
                }
            }
        }

		// when internal_channel is closed, close the output too
		close(channel)
    }()
    return channel, nil
}

/// Streaming version of AnalyzeBranchSecurityReviewer
func (*stream) AnalyzeBranchSecurityReviewer(ctx context.Context, prompt string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.SecurityReviewerOutput, types.SecurityReviewerOutput], error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchSecurityReviewer: %w", err)
        panic(wrapped_err)
    }

    internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchSecurityReviewer", encoded, callOpts.onTick)
    if err != nil {
        return nil, err
    }

    channel := make(chan StreamValue[stream_types.SecurityReviewerOutput, types.SecurityReviewerOutput])
    go func() {
        for result := range internal_channel {
            if result.Error != nil {
                channel <- StreamValue[stream_types.SecurityReviewerOutput, types.SecurityReviewerOutput]{
                    IsError: true,
                    Error:   result.Error,
                }
                close(channel)
                return
            }
            if result.HasData {
                    data := (result.Data).(types.SecurityReviewerOutput)
                    channel <- StreamValue[stream_types.SecurityReviewerOutput, types.SecurityReviewerOutput]{
                        IsFinal: true,
                        as_final: &data,
                    }
            } else {
                data := (result.StreamData).(stream_types.SecurityReviewerOutput)
                channel <- StreamValue[stream_types.SecurityReviewerOutput, types.SecurityReviewerOutput]{
                    IsFinal: false,
                    as_stream: &data,
                }
            }
        }

		// when internal_channel is closed, close the output too
		close(channel)
    }()
    return channel, nil
}

/// Streaming version of AnalyzeBranchStrictCritic
func (*stream) AnalyzeBranchStrictCritic(ctx context.Context, prompt string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.StrictCriticOutput, types.StrictCriticOutput], error) {

    var callOpts callOption
    for _, opt := range opts {
        opt(&callOpts)
    }

    args := baml.BamlFunctionArguments{
        Kwargs: map[string]any{ "prompt": prompt, },
        Env: getEnvVars(callOpts.env),
    }

    if callOpts.clientRegistry != nil {
        args.ClientRegistry = callOpts.clientRegistry
    }

    if callOpts.collectors != nil {
        args.Collectors = callOpts.collectors
    }

    if callOpts.typeBuilder != nil {
        args.TypeBuilder = callOpts.typeBuilder
    }

    if callOpts.tags != nil {
        args.Tags = callOpts.tags
    }

    encoded, err := args.Encode()
    if err != nil {
        // This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
        // and include the type of the args you're passing in.
        wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeBranchStrictCritic: %w", err)
        panic(wrapped_err)
    }

    internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeBranchStrictCritic", encoded, callOpts.onTick)
    if err != nil {
        return nil, err
    }

    channel := make(chan StreamValue[stream_types.StrictCriticOutput, types.StrictCriticOutput])
    go func() {
        for result := range internal_channel {
            if result.Error != nil {
                channel <- StreamValue[stream_types.StrictCriticOutput, types.StrictCriticOutput]{
                    IsError: true,
                    Error:   result.Error,
                }
                close(channel)
                return
            }
            if result.HasData {
                    data := (result.Data).(types.StrictCriticOutput)
                    channel <- StreamValue[stream_types.StrictCriticOutput, types.StrictCriticOutput]{
                        IsFinal: true,
                        as_final: &data,
                    }
            } else {
                data := (result.StreamData).(stream_types.StrictCriticOutput)
                channel <- StreamValue[stream_types.StrictCriticOutput, types.StrictCriticOutput]{
                    IsFinal: false,
                    as_stream: &data,
                }
            }
        }

		// when internal_channel is closed, close the output too
		close(channel)
    }()
    return channel, nil
}
