// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	_ "encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"

	_ "baml_client/baml_client/types"
)


type CreativeExplorerOutput struct {
    
Health_score *float64 `json:"health_score"`
Summary *string `json:"summary"`
Recommendations []string `json:"recommendations"`
Innovation_opportunities []string `json:"innovation_opportunities"`
Architectural_potential *string `json:"architectural_potential"`
    
}

func (c *CreativeExplorerOutput) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "CreativeExplorerOutput" {
		panic(fmt.Sprintf("expected CreativeExplorerOutput, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "health_score":
					c.Health_score = baml.Decode(valueHolder).Interface().(*float64)
				
				case "summary":
					c.Summary = baml.Decode(valueHolder).Interface().(*string)
				
				case "recommendations":
					c.Recommendations = baml.Decode(valueHolder).Interface().([]string)
				
				case "innovation_opportunities":
					c.Innovation_opportunities = baml.Decode(valueHolder).Interface().([]string)
				
				case "architectural_potential":
					c.Architectural_potential = baml.Decode(valueHolder).Interface().(*string)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class CreativeExplorerOutput", key))
			
		}
	}

}

func (c CreativeExplorerOutput) Encode() (*cffi.HostValue, error) {
    fields := map[string]any{}
    
    fields["health_score"] = c.Health_score
    
    fields["summary"] = c.Summary
    
    fields["recommendations"] = c.Recommendations
    
    fields["innovation_opportunities"] = c.Innovation_opportunities
    
    fields["architectural_potential"] = c.Architectural_potential
    
    return baml.EncodeClass("CreativeExplorerOutput", fields, nil)
}

func (c CreativeExplorerOutput) BamlTypeName() string {
    return "CreativeExplorerOutput"
}
type FindingSeverity struct {
    
Description *string `json:"description"`
Severity *string `json:"severity"`
    
}

func (c *FindingSeverity) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "FindingSeverity" {
		panic(fmt.Sprintf("expected FindingSeverity, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "description":
					c.Description = baml.Decode(valueHolder).Interface().(*string)
				
				case "severity":
					c.Severity = baml.Decode(valueHolder).Interface().(*string)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class FindingSeverity", key))
			
		}
	}

}

func (c FindingSeverity) Encode() (*cffi.HostValue, error) {
    fields := map[string]any{}
    
    fields["description"] = c.Description
    
    fields["severity"] = c.Severity
    
    return baml.EncodeClass("FindingSeverity", fields, nil)
}

func (c FindingSeverity) BamlTypeName() string {
    return "FindingSeverity"
}
type GeneralAnalystOutput struct {
    
Health_score *float64 `json:"health_score"`
Summary *string `json:"summary"`
Recommendations []string `json:"recommendations"`
Gaps []string `json:"gaps"`
Work_patterns *string `json:"work_patterns"`
    
}

func (c *GeneralAnalystOutput) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GeneralAnalystOutput" {
		panic(fmt.Sprintf("expected GeneralAnalystOutput, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "health_score":
					c.Health_score = baml.Decode(valueHolder).Interface().(*float64)
				
				case "summary":
					c.Summary = baml.Decode(valueHolder).Interface().(*string)
				
				case "recommendations":
					c.Recommendations = baml.Decode(valueHolder).Interface().([]string)
				
				case "gaps":
					c.Gaps = baml.Decode(valueHolder).Interface().([]string)
				
				case "work_patterns":
					c.Work_patterns = baml.Decode(valueHolder).Interface().(*string)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class GeneralAnalystOutput", key))
			
		}
	}

}

func (c GeneralAnalystOutput) Encode() (*cffi.HostValue, error) {
    fields := map[string]any{}
    
    fields["health_score"] = c.Health_score
    
    fields["summary"] = c.Summary
    
    fields["recommendations"] = c.Recommendations
    
    fields["gaps"] = c.Gaps
    
    fields["work_patterns"] = c.Work_patterns
    
    return baml.EncodeClass("GeneralAnalystOutput", fields, nil)
}

func (c GeneralAnalystOutput) BamlTypeName() string {
    return "GeneralAnalystOutput"
}
type RoleOutput struct {
    
Health_score *float64 `json:"health_score"`
Summary *string `json:"summary"`
Recommendations []string `json:"recommendations"`
    
}

func (c *RoleOutput) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "RoleOutput" {
		panic(fmt.Sprintf("expected RoleOutput, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "health_score":
					c.Health_score = baml.Decode(valueHolder).Interface().(*float64)
				
				case "summary":
					c.Summary = baml.Decode(valueHolder).Interface().(*string)
				
				case "recommendations":
					c.Recommendations = baml.Decode(valueHolder).Interface().([]string)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class RoleOutput", key))
			
		}
	}

}

func (c RoleOutput) Encode() (*cffi.HostValue, error) {
    fields := map[string]any{}
    
    fields["health_score"] = c.Health_score
    
    fields["summary"] = c.Summary
    
    fields["recommendations"] = c.Recommendations
    
    return baml.EncodeClass("RoleOutput", fields, nil)
}

func (c RoleOutput) BamlTypeName() string {
    return "RoleOutput"
}
type SecurityReviewerOutput struct {
    
Health_score *float64 `json:"health_score"`
Summary *string `json:"summary"`
Recommendations []string `json:"recommendations"`
Findings []FindingSeverity `json:"findings"`
    
}

func (c *SecurityReviewerOutput) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SecurityReviewerOutput" {
		panic(fmt.Sprintf("expected SecurityReviewerOutput, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "health_score":
					c.Health_score = baml.Decode(valueHolder).Interface().(*float64)
				
				case "summary":
					c.Summary = baml.Decode(valueHolder).Interface().(*string)
				
				case "recommendations":
					c.Recommendations = baml.Decode(valueHolder).Interface().([]string)
				
				case "findings":
					c.Findings = baml.Decode(valueHolder).Interface().([]FindingSeverity)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class SecurityReviewerOutput", key))
			
		}
	}

}

func (c SecurityReviewerOutput) Encode() (*cffi.HostValue, error) {
    fields := map[string]any{}
    
    fields["health_score"] = c.Health_score
    
    fields["summary"] = c.Summary
    
    fields["recommendations"] = c.Recommendations
    
    fields["findings"] = c.Findings
    
    return baml.EncodeClass("SecurityReviewerOutput", fields, nil)
}

func (c SecurityReviewerOutput) BamlTypeName() string {
    return "SecurityReviewerOutput"
}
type StrictCriticOutput struct {
    
Health_score *float64 `json:"health_score"`
Summary *string `json:"summary"`
Recommendations []string `json:"recommendations"`
Risks []string `json:"risks"`
    
}

func (c *StrictCriticOutput) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "StrictCriticOutput" {
		panic(fmt.Sprintf("expected StrictCriticOutput, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "health_score":
					c.Health_score = baml.Decode(valueHolder).Interface().(*float64)
				
				case "summary":
					c.Summary = baml.Decode(valueHolder).Interface().(*string)
				
				case "recommendations":
					c.Recommendations = baml.Decode(valueHolder).Interface().([]string)
				
				case "risks":
					c.Risks = baml.Decode(valueHolder).Interface().([]string)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class StrictCriticOutput", key))
			
		}
	}

}

func (c StrictCriticOutput) Encode() (*cffi.HostValue, error) {
    fields := map[string]any{}
    
    fields["health_score"] = c.Health_score
    
    fields["summary"] = c.Summary
    
    fields["recommendations"] = c.Recommendations
    
    fields["risks"] = c.Risks
    
    return baml.EncodeClass("StrictCriticOutput", fields, nil)
}

func (c StrictCriticOutput) BamlTypeName() string {
    return "StrictCriticOutput"
}