// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	_ "encoding/json"
	_ "fmt"

	_ "github.com/boundaryml/baml/engine/language_client_go/pkg"
	_ "github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"

	_ "baml_client/baml_client/types"
)

